apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-mypod
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  containers:
  - image: {{ .Values.image }}
    command: ["{{ .Values.command }}"]
    name: dummy-container
  dnsPolicy: ClusterFirst
  restartPolicy: Always